In [21]:
import numpy as np
def colmatrix():
    a = np.array([1,2,3,4])
    Y = 4
    print(np.vander(a,Y,increasing=False ))
colmatrix()



[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [26]:
import numpy as np
def movingaverage(x,w):
    m = np.convolve(x,w)
    print(m) 

In [27]:
x = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
w=3
movingaverage(x,w)

[  9  15  21   6  24  30  33 195 216 243 297 300 450]
